Name:           ros-indigo-hrpsys-gazebo-general
Version:        0.1.12
Release:        0%{?dist}
Summary:        ROS hrpsys_gazebo_general package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hrpsys_gazebo_general
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-collada-urdf-jsk-patch
Requires:       ros-indigo-gazebo-ros
Requires:       ros-indigo-hrpsys-gazebo-msgs
Requires:       ros-indigo-hrpsys-ros-bridge
Requires:       ros-indigo-turtlebot-description
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-collada-urdf-jsk-patch
BuildRequires:  ros-indigo-gazebo-ros
BuildRequires:  ros-indigo-hrpsys-gazebo-msgs
BuildRequires:  ros-indigo-hrpsys-ros-bridge

%description
hrpsys_gazebo_general

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Jan 11 2017 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.12-0
- Autogenerated by Bloom

* Tue Aug 30 2016 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.11-0
- Autogenerated by Bloom

* Thu Mar 24 2016 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.10-0
- Autogenerated by Bloom

* Fri Mar 18 2016 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.9-0
- Autogenerated by Bloom

