Name:           ros-hydro-staro-moveit-config
Version:        0.1.9
Release:        0%{?dist}
Summary:        ROS staro_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-joint-state-publisher
Requires:       ros-hydro-moveit-planners-ompl
Requires:       ros-hydro-moveit-ros-move-group
Requires:       ros-hydro-moveit-ros-visualization
Requires:       ros-hydro-robot-state-publisher
Requires:       ros-hydro-xacro
BuildRequires:  ros-hydro-catkin

%description
An automatically generated package with all the configuration and launch files
for using the STARO with the MoveIt Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Jun 19 2015 MoveIt Setup Assistant <assistant@moveit.ros.org> - 0.1.9-0
- Autogenerated by Bloom

* Fri Jan 09 2015 MoveIt Setup Assistant <assistant@moveit.ros.org> - 0.1.8-0
- Autogenerated by Bloom

* Fri Jan 09 2015 MoveIt Setup Assistant <assistant@moveit.ros.org> - 0.1.7-0
- Autogenerated by Bloom

* Thu Jan 08 2015 MoveIt Setup Assistant <assistant@moveit.ros.org> - 0.1.6-0
- Autogenerated by Bloom

