controller_list:
  - name: rarm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - RARM_SHOULDER_P
      - RARM_SHOULDER_R
      - RARM_SHOULDER_Y
      - RARM_ELBOW
      - RARM_WRIST_Y
      - RARM_WRIST_P
  - name: larm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - LARM_SHOULDER_P
      - LARM_SHOULDER_R
      - LARM_SHOULDER_Y
      - LARM_ELBOW
      - LARM_WRIST_Y
      - LARM_WRIST_P
  - name: torso_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - WAIST_P
      - WAIST_R
      - CHEST
