#### laser_scan_assembler
filters:
 - name: shadows
   type: laser_filters/ScanShadowsFilter
   params:
     min_angle: 10
     max_angle: 170
     neighbors: 20
     window: 1
 - name: through
   type: laser_filters/LaserScanRangeFilter
   params: 
## for localization
     # lower_threshold: 0.7
     # upper_threshold: 29.5
     lower_threshold: 0.3
     upper_threshold: 29.5
## for manipulation
#     lower_threshold: 0.3
#     upper_threshold: 2.8
 - name: intent
   type: laser_filters/LaserScanIntensityFilter
   params:
     lower_threshold: 750.0
     upper_threshold: 100000.0
     disp_histogram: 0
