#### laser_filters/scan_to_cloud_filter_chain
scan_filter_chain:
 - name: shadows
   type: laser_filters/ScanShadowsFilter
   params:
#     min_angle: 6
#     max_angle: 174
#     neighbors: 6
     min_angle: 8
     max_angle: 172
     neighbors: 14
     window: 1
 - name: through
   type: laser_filters/LaserScanRangeFilter
   params: 
# for localization
     lower_threshold: 0.5
     upper_threshold: 14.5
## comment out for gazebo
 - name: intent
   type: laser_filters/LaserScanIntensityFilter
   params:
     lower_threshold: 750.0
     upper_threshold: 100000.0
     disp_histogram: 0
#cloud_filter_chain:
