controller_list:
  - name: fake_larm_controller
    joints:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
  - name: fake_rarm_controller
    joints:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: fake_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
  - name: fake_lgripper_controller
    joints:
      - LARM_JOINT6
      - LARM_JOINT7
  - name: fake_rgripper_controller
    joints:
      - RARM_JOINT6
      - RARM_JOINT7
  - name: fake_larm_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
  - name: fake_rarm_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: fake_base_controller
    joints:
      - virtual_joint