joint_limits:
  LARM_JOINT0:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT2:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT3:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT4:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT5:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT6:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  LARM_JOINT7:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT0:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT2:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT3:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT4:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT5:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT6:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  RARM_JOINT7:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  CHEST_JOINT0:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  CHEST_JOINT1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 0.8
  R_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_palm_finger_middle_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_palm_finger_middle_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
